import type { Locale } from "@/i18n/config";

import {
  button,
  calloutPanel,
  divider,
  escapeHtml,
  factRows,
  orderedList,
  palette,
  paragraph,
  renderEmail,
  renderText,
  sectionLabel,
  statStrip,
  type EmailDocument,
  type Tone,
} from "./layout";

/**
 * "Your tender report is ready."
 *
 * The report takes minutes to write and nobody sits watching the progress bar,
 * so this email is how the analysis actually reaches the team. It therefore has
 * to be readable on its own: a recipient who never opens the link should still
 * come away knowing the verdict, the deadline and whether anything is on fire.
 *
 * What it deliberately does NOT do is reproduce the report. Requirements, risks
 * and evidence belong on the page, where they can be cited and exported; an
 * email that tried to carry them would be unreadable and instantly stale.
 */

export type ReportDecision = "bid" | "conditional" | "no_bid";

export interface ReportReadyData {
  tenderTitle: string;
  buyerName: string | null;
  submissionDeadline: Date | null;
  companyName: string | null;
  decision: ReportDecision;
  /** 0..1, as stored on the report. */
  confidence: number;
  /** Opening paragraph of the executive summary. */
  headline: string;
  requirementCount: number;
  gapCount: number;
  highRiskCount: number;
  /** The `immediate` priority actions, in order. */
  immediateActions: string[];
  reportUrl: string;
  /** Who pressed generate — omitted when it was the recipient themselves. */
  requestedByName: string | null;
}

const DECISION_TONE: Record<ReportDecision, Tone> = {
  bid: "positive",
  conditional: "caution",
  no_bid: "critical",
};

const DECISION_INK: Record<ReportDecision, string> = {
  bid: palette.positiveInk,
  conditional: palette.cautionInk,
  no_bid: palette.criticalInk,
};

const copy = {
  en: {
    // Labels below mirror `Tenders.report.*` in messages/en.json on purpose:
    // the email is the first thing a reader sees and must use the same words
    // as the page it links to.
    decision: {
      bid: "Bid",
      conditional: "Bid — conditionally",
      no_bid: "Do not bid",
    },
    subject: (title: string) => `Tender report ready: ${title}`,
    preheader: (decision: string, deadline: string | null) =>
      deadline
        ? `Recommendation: ${decision} · Submission deadline ${deadline}`
        : `Recommendation: ${decision}`,
    eyebrow: "Analysis complete",
    title: "Your tender report is ready",
    intro: (tender: string) =>
      `BAU AI has finished the full analysis of “${tender}”. Here is the short version — the complete report, with every requirement, risk and source, is waiting in your workspace.`,
    requestedBy: (name: string) => `Generated by ${name}.`,
    confidence: (value: string) => `${value} confidence`,
    summaryLabel: "Executive summary",
    factsLabel: "At a glance",
    buyer: "Contracting authority",
    deadline: "Submission deadline",
    preparedFor: "Prepared for",
    notProvided: "Not provided",
    stats: {
      requirements: "Requirements assessed",
      gaps: "Requirement gaps",
      risks: "High risks",
    },
    actionsLabel: "Do these first",
    button: "Open the full report",
    disclaimer:
      "This analysis is AI-generated decision support. Verify every deadline, requirement and figure against the original tender documents before submitting.",
    footerNote: (company: string | null) =>
      company
        ? `You are receiving this email because you are a member of ${company} on BAU AI.`
        : "You are receiving this email because you are a member of this company on BAU AI.",
    deadlinePassed: "Deadline passed",
    deadlineDays: (days: number) =>
      days === 0
        ? "Due today"
        : days === 1
          ? "1 day left"
          : `${days} days left`,
  },
  de: {
    decision: {
      bid: "Angebot abgeben",
      conditional: "Angebot — unter Bedingungen",
      no_bid: "Nicht anbieten",
    },
    subject: (title: string) => `Ausschreibungsbericht fertig: ${title}`,
    preheader: (decision: string, deadline: string | null) =>
      deadline
        ? `Empfehlung: ${decision} · Abgabefrist ${deadline}`
        : `Empfehlung: ${decision}`,
    eyebrow: "Analyse abgeschlossen",
    title: "Ihr Ausschreibungsbericht ist fertig",
    intro: (tender: string) =>
      `BAU AI hat die vollständige Analyse von „${tender}“ abgeschlossen. Hier die Kurzfassung — der komplette Bericht mit allen Anforderungen, Risiken und Quellen liegt in Ihrem Workspace bereit.`,
    requestedBy: (name: string) => `Erstellt von ${name}.`,
    confidence: (value: string) => `${value} Konfidenz`,
    summaryLabel: "Zusammenfassung",
    factsLabel: "Auf einen Blick",
    buyer: "Auftraggeber",
    deadline: "Abgabefrist",
    preparedFor: "Erstellt für",
    notProvided: "Nicht angegeben",
    stats: {
      requirements: "Geprüfte Anforderungen",
      gaps: "Offene Lücken",
      risks: "Hohe Risiken",
    },
    actionsLabel: "Das zuerst erledigen",
    button: "Vollständigen Bericht öffnen",
    disclaimer:
      "Diese Analyse ist KI-gestützte Entscheidungshilfe. Prüfen Sie jede Frist, Anforderung und Zahl vor der Abgabe anhand der Originalunterlagen.",
    footerNote: (company: string | null) =>
      company
        ? `Sie erhalten diese E-Mail, weil Sie Mitglied von ${company} bei BAU AI sind.`
        : "Sie erhalten diese E-Mail, weil Sie Mitglied dieses Unternehmens bei BAU AI sind.",
    deadlinePassed: "Frist abgelaufen",
    deadlineDays: (days: number) =>
      days === 0
        ? "Heute fällig"
        : days === 1
          ? "1 Tag verbleibend"
          : `${days} Tage verbleibend`,
  },
} as const;

/** German deadlines are German deadlines — never render them in the host's zone. */
function formatDate(date: Date, locale: Locale): string {
  return new Intl.DateTimeFormat(locale === "de" ? "de-DE" : "en-GB", {
    dateStyle: "long",
    timeZone: "Europe/Berlin",
  }).format(date);
}

function daysUntil(date: Date): number {
  return Math.ceil((date.getTime() - Date.now()) / 86_400_000);
}

/** The executive summary opener, trimmed to something an inbox will show. */
function trimHeadline(text: string, limit = 340): string {
  const collapsed = text.replace(/\s+/g, " ").trim();
  if (collapsed.length <= limit) return collapsed;
  const cut = collapsed.slice(0, limit);
  const boundary = cut.lastIndexOf(" ");
  return `${(boundary > limit * 0.6 ? cut.slice(0, boundary) : cut).replace(/[,;:.\s]+$/, "")}…`;
}

export function reportReadyEmail({
  locale,
  data,
}: {
  locale: Locale;
  data: ReportReadyData;
}): EmailDocument {
  const message = copy[locale];
  const decisionLabel = message.decision[data.decision];
  const decisionTone = DECISION_TONE[data.decision];
  const confidence = `${Math.round(Math.max(0, Math.min(1, data.confidence)) * 100)}%`;
  const deadline = data.submissionDeadline
    ? formatDate(data.submissionDeadline, locale)
    : null;

  const remaining = data.submissionDeadline
    ? daysUntil(data.submissionDeadline)
    : null;
  const deadlineValue =
    deadline && remaining !== null
      ? remaining < 0
        ? `${deadline} · ${message.deadlinePassed}`
        : `${deadline} · ${message.deadlineDays(remaining)}`
      : message.notProvided;

  const facts: Array<{ label: string; value: string }> = [
    { label: message.buyer, value: data.buyerName ?? message.notProvided },
    { label: message.deadline, value: deadlineValue },
  ];
  if (data.companyName) {
    facts.push({ label: message.preparedFor, value: data.companyName });
  }

  const actions = data.immediateActions.slice(0, 3);

  const content = [
    paragraph(message.intro(data.tenderTitle), { spaceAfter: 24 }),

    // Verdict first: it is the one thing a reader must not have to hunt for.
    calloutPanel(
      [
        `<table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="margin:0 0 10px"><tr>
          <td class="bau-stack" align="left" valign="bottom" style="color:${DECISION_INK[data.decision]};font-size:17px;font-weight:700;letter-spacing:-.02em;line-height:1.3;mso-line-height-rule:exactly">${escapeHtml(decisionLabel)}</td>
          <td class="bau-muted bau-stack" align="right" valign="bottom" style="color:${palette.muted};font-size:12px;white-space:nowrap;line-height:1.3;mso-line-height-rule:exactly">${escapeHtml(message.confidence(confidence))}</td>
        </tr></table>`,
        paragraph(trimHeadline(data.headline), { spaceAfter: 0 }),
      ].join(""),
      decisionTone,
    ),

    statStrip([
      {
        label: message.stats.requirements,
        value: String(data.requirementCount),
      },
      {
        label: message.stats.gaps,
        value: String(data.gapCount),
        tone: data.gapCount > 0 ? "caution" : "positive",
      },
      {
        label: message.stats.risks,
        value: String(data.highRiskCount),
        tone: data.highRiskCount > 0 ? "critical" : "positive",
      },
    ]),

    sectionLabel(message.factsLabel),
    factRows(facts),

    ...(actions.length > 0
      ? [sectionLabel(message.actionsLabel), orderedList(actions)]
      : []),

    button({ href: data.reportUrl, label: message.button }),

    ...(data.requestedByName
      ? [
          paragraph(message.requestedBy(data.requestedByName), {
            tone: "muted",
            spaceAfter: 4,
          }),
        ]
      : []),

    divider(),
    paragraph(message.disclaimer, { tone: "muted", spaceAfter: 0 }),
  ].join("");

  return {
    subject: message.subject(data.tenderTitle),
    html: renderEmail({
      locale,
      preheader: message.preheader(decisionLabel, deadline),
      eyebrow: message.eyebrow,
      title: message.title,
      content,
      footerNote: message.footerNote(data.companyName),
    }),
    text: renderText({
      locale,
      title: message.title,
      lines: [
        message.intro(data.tenderTitle),
        "",
        `${decisionLabel} (${message.confidence(confidence)})`,
        "",
        trimHeadline(data.headline),
        "",
        `${message.stats.requirements}: ${data.requirementCount}`,
        `${message.stats.gaps}: ${data.gapCount}`,
        `${message.stats.risks}: ${data.highRiskCount}`,
        "",
        `${message.buyer}: ${data.buyerName ?? message.notProvided}`,
        `${message.deadline}: ${deadlineValue}`,
        ...(data.companyName
          ? [`${message.preparedFor}: ${data.companyName}`]
          : []),
        ...(actions.length > 0
          ? [
              "",
              `${message.actionsLabel}:`,
              ...actions.map((action, index) => `${index + 1}. ${action}`),
            ]
          : []),
        "",
        `${message.button}: ${data.reportUrl}`,
        ...(data.requestedByName
          ? ["", message.requestedBy(data.requestedByName)]
          : []),
        "",
        message.disclaimer,
      ],
    }),
  };
}
