import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

/**
 * PDF fill fixtures, as an importable MODULE rather than an out-of-band script.
 *
 * Phase 1's Word fixture was generated by scripts/test-fixtures/
 * generate-document-fill-fixture.py, which emits no w:sdt content controls —
 * yet docx-fill.test.ts asserts form_key locators resolve against the committed
 * .docx. The binary and its generator diverged and nothing catches it. Here the
 * generator IS the fixture: tests call these functions directly, so drift is
 * structurally impossible.
 *
 * pdf-lib output is byte-deterministic given a fixed creation/modification date
 * and {useObjectStreams:false}, so golden-hash assertions on these are
 * meaningful.
 */

const A4: [number, number] = [595.28, 841.89];

function freeze(doc: PDFDocument) {
  doc.setCreationDate(new Date(0));
  doc.setModificationDate(new Date(0));
}

/**
 * An interactive German form exercising every branch resolve-pdf cares about:
 * each fillable widget type, a read-only field, a signature field, a field with
 * TWO linked widgets (legitimate — one value, many places), and a dropdown
 * whose options constrain what may be written.
 */
export async function makeAcroFormFixture(): Promise<Buffer> {
  const doc = await PDFDocument.create();
  freeze(doc);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const page1 = doc.addPage(A4);
  const page2 = doc.addPage(A4);
  const form = doc.getForm();

  page1.drawText("Eigenerklärung zur Eignung", { x: 56, y: 790, size: 16, font: bold });
  page1.drawText("Vergabeverfahren VG-2026-0041 — Neubau Sporthalle", {
    x: 56,
    y: 766,
    size: 10,
    font,
  });

  const label = (text: string, y: number) =>
    page1.drawText(text, { x: 56, y: y + 5, size: 10, font, color: rgb(0, 0, 0) });

  label("Name des Unternehmens:", 720);
  form.createTextField("company.name").addToPage(page1, { x: 240, y: 716, width: 300, height: 18 });

  label("Umsatzsteuer-Identifikationsnummer:", 690);
  form.createTextField("company.vat").addToPage(page1, { x: 240, y: 686, width: 200, height: 18 });

  label("Straße und Hausnummer:", 660);
  form.createTextField("company.street").addToPage(page1, { x: 240, y: 656, width: 300, height: 18 });

  label("PLZ und Ort:", 630);
  form.createTextField("company.city").addToPage(page1, { x: 240, y: 626, width: 300, height: 18 });

  label("Anzahl der Beschäftigten:", 600);
  form.createTextField("company.employees").addToPage(page1, { x: 240, y: 596, width: 120, height: 18 });

  label("Präqualifiziert:", 570);
  form.createCheckBox("company.prequalified").addToPage(page1, { x: 240, y: 568, width: 14, height: 14 });

  label("Rechtsform:", 540);
  const legalForm = form.createDropdown("company.legalForm");
  legalForm.addOptions(["GmbH", "AG", "GmbH & Co. KG", "Einzelunternehmen"]);
  legalForm.addToPage(page1, { x: 240, y: 536, width: 200, height: 18 });

  label("Schwerpunkt:", 510);
  const trade = form.createRadioGroup("company.trade");
  trade.addOptionToPage("Hochbau", page1, { x: 240, y: 508, width: 14, height: 14 });
  trade.addOptionToPage("Tiefbau", page1, { x: 320, y: 508, width: 14, height: 14 });

  // Read-only: pre-set by the issuer, never fillable.
  label("Aktenzeichen:", 480);
  const reference = form.createTextField("meta.reference");
  reference.setText("VG-2026-0041");
  reference.addToPage(page1, { x: 240, y: 476, width: 200, height: 18 });
  reference.enableReadOnly();

  // ONE field, TWO widgets on different pages — must share a single value.
  label("Kürzel:", 450);
  const initials = form.createTextField("company.initials");
  initials.addToPage(page1, { x: 240, y: 446, width: 80, height: 18 });
  page2.drawText("Kürzel (Wiederholung):", { x: 56, y: 795, size: 10, font });
  initials.addToPage(page2, { x: 240, y: 790, width: 80, height: 18 });

  // Sensitive: must always land in `manual`, never auto-filled.
  page2.drawText("Rechtsverbindliche Unterschrift:", { x: 56, y: 745, size: 10, font });
  form
    .createTextField("signature.authorized")
    .addToPage(page2, { x: 240, y: 740, width: 260, height: 24 });

  page2.drawText("IBAN:", { x: 56, y: 705, size: 10, font });
  form.createTextField("bank.iban").addToPage(page2, { x: 240, y: 700, width: 260, height: 18 });

  form.updateFieldAppearances(font);
  return Buffer.from(await doc.save({ useObjectStreams: false }));
}

/**
 * A flat German form: a real text layer, no interactive fields. Labels are
 * followed by underscore runs.
 *
 * Deliberate traps:
 *  - "Ansprechpartner:" appears on BOTH pages, so it is a globally ambiguous
 *    anchor and must be rejected by the uniqueness rule.
 *  - every underscore run is byte-identical, proving the anchor cannot be the
 *    blank itself (probe P2.B showed the model reaching for exactly that).
 *  - page 2 is rotated 90°, so coordinates must stay in unrotated user space.
 */
export async function makeDigitalFixture(): Promise<Buffer> {
  const doc = await PDFDocument.create();
  freeze(doc);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const blank = "______________________________";

  const page1 = doc.addPage(A4);
  let y = 790;
  const line = (text: string, f = font, size = 11) => {
    page1.drawText(text, { x: 56, y, size, font: f, color: rgb(0, 0, 0) });
    y -= 28;
  };
  line("Eigenerklärung zur Eignung", bold, 16);
  line("Vergabeverfahren VG-2026-0041 — Neubau Sporthalle Düsseldorf");
  y -= 8;
  line(`Name des Unternehmens: ${blank}`);
  line(`Rechtsform: ${blank}`);
  line(`Straße und Hausnummer: ${blank}`);
  line(`PLZ und Ort: ${blank}`);
  line(`Umsatzsteuer-Identifikationsnummer: ${blank}`);
  line(`Anzahl der Beschäftigten: ${blank}`);
  line(`Ansprechpartner: ${blank}`);
  line(`IBAN: ${blank}`);
  y -= 10;
  line("Ich erkläre, dass die vorstehenden Angaben zutreffend sind.");
  line(`Ort, Datum: ${blank}`);
  line(`Rechtsverbindliche Unterschrift: ${blank}`);

  const page2 = doc.addPage(A4);
  page2.setRotation({ type: "degrees", angle: 90 } as never);
  page2.drawText("Anlage 1 — Referenzen", { x: 56, y: 790, size: 14, font: bold });
  // Duplicate label: globally ambiguous, must never produce a locator.
  page2.drawText(`Ansprechpartner: ${blank}`, { x: 56, y: 740, size: 11, font });
  page2.drawText(`Referenzprojekt: ${blank}`, { x: 56, y: 700, size: 11, font });

  return Buffer.from(await doc.save({ useObjectStreams: false }));
}

/**
 * A page with no text layer at all — the `scanned` class. Real scans cannot be
 * synthesized, but the property that matters here is the ABSENCE of extractable
 * text, and a vector-only page has exactly that.
 */
export async function makeScannedLikeFixture(): Promise<Buffer> {
  const doc = await PDFDocument.create();
  freeze(doc);
  const page = doc.addPage(A4);
  // Rules and boxes suggesting a form, drawn as vectors: nothing to extract.
  for (let i = 0; i < 8; i++) {
    const y = 720 - i * 42;
    page.drawLine({
      start: { x: 240, y },
      end: { x: 540, y },
      thickness: 0.75,
      color: rgb(0.1, 0.1, 0.1),
    });
    page.drawRectangle({
      x: 56,
      y: y + 2,
      width: 150,
      height: 12,
      borderWidth: 0.5,
      borderColor: rgb(0.6, 0.6, 0.6),
    });
  }
  return Buffer.from(await doc.save({ useObjectStreams: false }));
}
